// approach-c/src/components/DetailPanel.svelte
<script lang="ts">
  import { selectedParcel, selectedDetail, detailLoading } from '../store'
  import PriceChart from './PriceChart.svelte'

  const fmt = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })

  function close() {
    selectedParcel.set(null)
    selectedDetail.set(null)
  }
</script>

<!-- svelte-ignore a11y_interactive_supports_focus a11y_no_noninteractive_element_interactions -->
<div class="panel-overlay" on:click={close} on:keydown={(e) => e.key === 'Escape' && close()} role="dialog" aria-modal="true" tabindex="-1">
  <div class="panel" on:click|stopPropagation on:keydown|stopPropagation role="presentation">
    <div class="panel-header">
      <div>
        <h2>{$selectedParcel?.address}</h2>
        <span class="account">Account: {$selectedParcel?.account}</span>
      </div>
      <button class="close-btn" on:click={close}>x</button>
    </div>

    {#if $detailLoading}
      <div class="loading">Loading details...</div>
    {:else if $selectedDetail}
      <div class="panel-body">
        <!-- Key Stats Grid -->
        <div class="stats-grid">
          <div class="stat">
            <span class="stat-label">Last Sale</span>
            <span class="stat-value">{fmt.format($selectedParcel?.last_sale_price ?? 0)}</span>
            <span class="stat-sub">{$selectedParcel?.last_sale_date}</span>
          </div>
          <div class="stat">
            <span class="stat-label">$/sqft</span>
            <span class="stat-value">${$selectedParcel?.price_per_sqft?.toFixed(0) ?? 'N/A'}</span>
          </div>
          <div class="stat">
            <span class="stat-label">$/sqft Lot</span>
            <span class="stat-value">${$selectedParcel?.price_per_sqft_lot?.toFixed(0) ?? 'N/A'}</span>
          </div>
          <div class="stat">
            <span class="stat-label">Living</span>
            <span class="stat-value">{$selectedParcel?.sqft_living.toLocaleString()}</span>
            <span class="stat-sub">sqft</span>
          </div>
          <div class="stat">
            <span class="stat-label">Lot</span>
            <span class="stat-value">{$selectedParcel?.sqft_lot.toLocaleString()}</span>
            <span class="stat-sub">sqft</span>
          </div>
          <div class="stat">
            <span class="stat-label">Built</span>
            <span class="stat-value">{$selectedParcel?.year_built}</span>
          </div>
          <div class="stat">
            <span class="stat-label">Assessed</span>
            <span class="stat-value">{fmt.format($selectedParcel?.assessed_value ?? 0)}</span>
          </div>
        </div>

        <!-- Price Trajectory Chart -->
        {#if $selectedDetail.sales.length > 1}
          <div class="section">
            <h3>Price History</h3>
            <PriceChart sales={$selectedDetail.sales} />
          </div>
        {/if}

        <!-- Sales History Table -->
        <div class="section">
          <h3>Sales ({$selectedDetail.sales.length})</h3>
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Price</th>
                <th>Type</th>
              </tr>
            </thead>
            <tbody>
              {#each $selectedDetail.sales as sale}
                <tr>
                  <td>{sale.date}</td>
                  <td>{fmt.format(sale.price)}</td>
                  <td class="deed-type">{sale.type}</td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>

        <!-- Permits -->
        {#if $selectedDetail.permits.length > 0}
          <div class="section">
            <h3>Permits ({$selectedDetail.permits.length})</h3>
            <table>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Type</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {#each $selectedDetail.permits as permit}
                  <tr>
                    <td>{permit.date}</td>
                    <td>{permit.type}</td>
                    <td>
                      <span class="status" class:final={permit.status === 'FINAL'} class:active={permit.status === 'ACTIVE' || permit.status === 'ISSUED'}>
                        {permit.status}
                      </span>
                    </td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        {/if}

        <!-- Improvements -->
        {#if $selectedDetail.improvements.length > 0}
          <div class="section">
            <h3>Improvements ({$selectedDetail.improvements.length})</h3>
            <div class="improvements">
              {#each $selectedDetail.improvements as imp}
                <div class="improvement">
                  <span class="imp-type">{imp.type}</span>
                  <span class="imp-detail">{imp.sqft.toLocaleString()} sqft | Built {imp.year_built}</span>
                  <span class="imp-condition">{imp.condition}</span>
                </div>
              {/each}
            </div>
          </div>
        {/if}
      </div>
    {:else}
      <div class="loading">No detail data available</div>
    {/if}
  </div>
</div>

<style>
  .panel-overlay {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.3);
    z-index: 30;
    display: flex;
    align-items: flex-end;
    justify-content: center;
  }

  .panel {
    background: rgba(26, 26, 46, 0.97);
    backdrop-filter: blur(12px);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 16px 16px 0 0;
    width: 100%;
    max-width: 500px;
    max-height: 80vh;
    overflow-y: auto;
    padding: 20px;
    animation: slideUp 0.25s ease-out;
  }

  @keyframes slideUp {
    from { transform: translateY(100%); }
    to { transform: translateY(0); }
  }

  .panel-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 16px;
  }

  h2 {
    font-size: 18px;
    color: #e0e0e0;
    font-weight: 700;
  }

  .account {
    font-size: 11px;
    color: #6666aa;
  }

  .close-btn {
    background: rgba(255, 255, 255, 0.1);
    border: none;
    color: #a0a0c0;
    width: 32px;
    height: 32px;
    border-radius: 8px;
    font-size: 16px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .close-btn:hover {
    background: rgba(255, 255, 255, 0.2);
  }

  .loading {
    padding: 40px;
    text-align: center;
    color: #8888aa;
  }

  .panel-body {
    display: flex;
    flex-direction: column;
    gap: 20px;
  }

  .stats-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 10px;
  }

  .stat {
    background: rgba(255, 255, 255, 0.04);
    border-radius: 8px;
    padding: 10px;
    text-align: center;
  }

  .stat-label {
    display: block;
    font-size: 10px;
    color: #6666aa;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin-bottom: 2px;
  }

  .stat-value {
    display: block;
    font-size: 16px;
    font-weight: 700;
    color: #e0e0e0;
  }

  .stat-sub {
    display: block;
    font-size: 10px;
    color: #8888aa;
  }

  .section h3 {
    font-size: 13px;
    color: #a0a0c0;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin-bottom: 8px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.06);
    padding-bottom: 4px;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 12px;
  }

  th {
    text-align: left;
    color: #6666aa;
    font-weight: 600;
    padding: 4px 8px;
    font-size: 10px;
    text-transform: uppercase;
  }

  td {
    padding: 6px 8px;
    color: #c0c0d0;
    border-top: 1px solid rgba(255, 255, 255, 0.04);
  }

  .deed-type {
    font-size: 10px;
    color: #8888aa;
  }

  .status {
    font-size: 10px;
    padding: 2px 6px;
    border-radius: 4px;
    background: rgba(255, 255, 255, 0.06);
  }

  .status.final {
    background: rgba(80, 200, 120, 0.15);
    color: #50c878;
  }

  .status.active {
    background: rgba(100, 100, 255, 0.15);
    color: #8888ff;
  }

  .improvements {
    display: flex;
    flex-direction: column;
    gap: 6px;
  }

  .improvement {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 8px 10px;
    background: rgba(255, 255, 255, 0.04);
    border-radius: 6px;
  }

  .imp-type {
    font-weight: 600;
    font-size: 12px;
    color: #c0c0d0;
    min-width: 70px;
  }

  .imp-detail {
    font-size: 11px;
    color: #8888aa;
    flex: 1;
  }

  .imp-condition {
    font-size: 10px;
    color: #6666aa;
    text-transform: uppercase;
  }

  @media (max-width: 480px) {
    .stats-grid {
      grid-template-columns: repeat(2, 1fr);
    }

    .panel {
      max-height: 90vh;
    }
  }
</style>

// approach-a/src/components/DetailPanel.jsx
import { useEffect, useState } from 'react'
import { loadParcelDetail } from '../utils/data'

export default function DetailPanel({ parcel, onClose, onCompare, isInCompare }) {
  const [detail, setDetail] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!parcel) return
    setLoading(true)
    setDetail(null)
    loadParcelDetail(parcel.account).then(d => {
      setDetail(d)
      setLoading(false)
    })
  }, [parcel?.account])

  if (!parcel) return null

  return (
    <div className="detail-panel">
      <div className="detail-header">
        <div>
          <h2>{parcel.address || `Parcel ${parcel.account}`}</h2>
          <span className="detail-account">Account: {parcel.account}</span>
        </div>
        <div className="detail-actions">
          {onCompare && (
            <button
              className={`compare-btn ${isInCompare ? 'active' : ''}`}
              onClick={() => onCompare(parcel)}
              disabled={isInCompare}
            >
              {isInCompare ? 'In Compare' : '+ Compare'}
            </button>
          )}
          <button className="detail-close" onClick={onClose}>&times;</button>
        </div>
      </div>

      <div className="detail-body">
        <div className="detail-stats">
          <StatCard label="$/sqft" value={parcel.price_per_sqft ? `$${Math.round(parcel.price_per_sqft)}` : 'N/A'} />
          <StatCard label="$/sqft Lot" value={parcel.price_per_sqft_lot ? `$${Math.round(parcel.price_per_sqft_lot)}` : 'N/A'} />
          <StatCard label="Last Sale" value={parcel.last_sale_price ? `$${(parcel.last_sale_price / 1000).toFixed(0)}k` : 'N/A'} />
          <StatCard label="Assessed" value={parcel.assessed_value ? `$${(parcel.assessed_value / 1000).toFixed(0)}k` : 'N/A'} />
          <StatCard label="Year Built" value={parcel.year_built || 'N/A'} />
          <StatCard label="Living Sqft" value={parcel.sqft_living ? parcel.sqft_living.toLocaleString() : 'N/A'} />
          <StatCard label="Lot Sqft" value={parcel.sqft_lot ? parcel.sqft_lot.toLocaleString() : 'N/A'} />
        </div>

        {loading && <div className="detail-loading">Loading details...</div>}

        {detail && (
          <>
            {detail.sales && detail.sales.length > 0 && (
              <div className="detail-section">
                <h3>Sales History</h3>
                <PriceChart sales={detail.sales} />
                <table className="sales-table">
                  <thead>
                    <tr><th>Date</th><th>Price</th><th>Type</th></tr>
                  </thead>
                  <tbody>
                    {detail.sales.map((s, i) => (
                      <tr key={i}>
                        <td>{s.date}</td>
                        <td>{s.price ? `$${s.price.toLocaleString()}` : 'N/A'}</td>
                        <td>{s.type}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {detail.permits && detail.permits.length > 0 && (
              <div className="detail-section">
                <h3>Permits ({detail.permits.length})</h3>
                <table className="permits-table">
                  <thead>
                    <tr><th>Date</th><th>Type</th><th>Status</th></tr>
                  </thead>
                  <tbody>
                    {detail.permits.map((p, i) => (
                      <tr key={i}>
                        <td>{p.date}</td>
                        <td>{p.type}</td>
                        <td><span className={`status-badge ${p.status.toLowerCase()}`}>{p.status}</span></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {detail.improvements && detail.improvements.length > 0 && (
              <div className="detail-section">
                <h3>Improvements</h3>
                <div className="improvements-list">
                  {detail.improvements.map((imp, i) => (
                    <div key={i} className="improvement-card">
                      <strong>{imp.type}</strong>
                      <span>{imp.sqft ? `${imp.sqft.toLocaleString()} sqft` : ''}</span>
                      <span>{imp.year_built ? `Built ${imp.year_built}` : ''}</span>
                      <span className="condition">{imp.condition}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </>
        )}

        {!loading && !detail && (
          <div className="detail-empty">No detailed data available for this parcel.</div>
        )}
      </div>
    </div>
  )
}

function StatCard({ label, value }) {
  return (
    <div className="stat-card">
      <div className="stat-value">{value}</div>
      <div className="stat-label">{label}</div>
    </div>
  )
}

function PriceChart({ sales }) {
  const validSales = sales
    .filter(s => s.price && s.date)
    .sort((a, b) => new Date(a.date) - new Date(b.date))

  if (validSales.length < 2) return null

  const prices = validSales.map(s => s.price)
  const minPrice = Math.min(...prices)
  const maxPrice = Math.max(...prices)
  const range = maxPrice - minPrice || 1

  const width = 300
  const height = 120
  const padding = { top: 10, right: 10, bottom: 20, left: 10 }
  const chartW = width - padding.left - padding.right
  const chartH = height - padding.top - padding.bottom

  const points = validSales.map((s, i) => {
    const x = padding.left + (i / (validSales.length - 1)) * chartW
    const y = padding.top + chartH - ((s.price - minPrice) / range) * chartH
    return { x, y, ...s }
  })

  const pathD = points.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x} ${p.y}`).join(' ')

  return (
    <div className="price-chart">
      <svg viewBox={`0 0 ${width} ${height}`} width="100%" preserveAspectRatio="xMidYMid meet">
        <path d={pathD} fill="none" stroke="#4292c6" strokeWidth="2" />
        {points.map((p, i) => (
          <g key={i}>
            <circle cx={p.x} cy={p.y} r="4" fill="#4292c6" />
            <text x={p.x} y={height - 4} textAnchor="middle" fontSize="9" fill="#666">
              {new Date(p.date).getFullYear()}
            </text>
          </g>
        ))}
        <text x={padding.left} y={padding.top + 4} fontSize="9" fill="#666">
          ${(maxPrice / 1000).toFixed(0)}k
        </text>
        <text x={padding.left} y={padding.top + chartH} fontSize="9" fill="#666">
          ${(minPrice / 1000).toFixed(0)}k
        </text>
      </svg>
    </div>
  )
}
